"project_id": "498233"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files:
  [
    {
      "source": "/ChatThree/Resources/Language.resx",
      "translation": "/ChatThree/Resources/Language.%two_letters_code%.resx",
      "dest": "/Language.resx",
      "skip_untranslated_strings": true,
    },
  ]
